project:
  type: website

website:
  title: "Capstone Project"
  navbar:
    left:
      - href: index.qmd
        text: Visualizations

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  
editor: visual
